### PR TITLE
#162 - twister

### PR DESCRIPTION
**Pull request by ultimatefiend**
This has overlap with Communist Manifesto (some of the reveal->board transitions).

Also, there is a Javascript bug when more than two cards are revealed from your score pile.  If you refresh the page, the cards are in the reveal area though.

### CODE REVIEW

**Comment by micahstairs** [comment]
Okay I rebased this with the latest version of main-dev (which included the Communist Manifesto changes), so before you continue working on this branch, you need to `git pull` first.

So in your proposed implementation, you are getting the player to select a color and then getting them to meld a card of that color. What do you think of doing this in one step instead of two? For the first card we meld, we let the player choose any color, and then for succeeding melds, we reduce the colors that they are allowed to choose.

What do you think of this idea? If you like it, I will add support to the 'color' option to work in this situation (right now the 'color' option is only used for choosing colors, not choosing cards).

**Comment by ultimatefiend** [comment]
I think that's a brilliant idea.  Much simpler.

Do we need to add anything?  We could even return the cards to the score pile you can't choose from (i.e. the colors that have been chosen already) so its not as confusing.

**Comment by ultimatefiend** [comment]
Alternatively, the user could choose a color, reveal just those colors and then choose from one of them.

That might limit the number of cards that need to be shown at a time (it could be a lot).

**Comment by micahstairs** [comment]
Okay, for simplicity, how about we reveal all cards from the score pile, and then each time the player chooses a color, we return the other cards of that color.

Please leave a TODO to improve this once we have a mechanism to dump out a list of cards to the log. I think that will be a better long-term solution. But it will also involve us adding support for filtering the cards by their color (which will be relatively easy to do).

How does that sound to you?

**Comment by ultimatefiend** [comment]
Sounds good.

**Comment by ultimatefiend** [comment]
Much simpler now!

**Review by micahstairs — APPROVED** [review]
Thanks for simplifying this!

**Pull request merged**
