### PR TITLE
age 8 world cup #145

### PR DESCRIPTION
**Pull request by ultimatefiend**

### CODE REVIEW

**Comment by ultimatefiend** [comment]
You probably want to inspect the achievement removing/decrementing of the score on the UI carefully.  I'm not sure its working totally right.

**Comment by micahstairs** [comment]
Okay I think you want to make an equivalent to this for decrementing the score in the JavaScript file:

```
            // Update BGA score if needed
            if(card.location_to == 'achievements') {
                // Increment player BGA score (all the team in team game)
                var player_team = this.players[card.owner_to].player_team;
                for(var player_id in this.players) {
                    if (this.players[player_id].player_team == player_team) {
                        this.scoreCtrl[player_id].incValue(1);
                    }
                }
            }
```

**Comment by ultimatefiend** [comment]
Its not clear how to do the JS.  I have this:

            if(card.location_from == 'achievements') {
                // Increment player BGA score (all the team in team game)
                var player_team = this.players[card.owner_from].player_team;
                for(var player_id in this.players) {
                    if (this.players[player_id].player_team == player_team) {
                        this.scoreCtrl[player_id].incValue(-1);
                    }
                }
            }

That's not quite right because you also want to make sure when an achievement->achievement transfer occurs that the number doesn't go down.  So you want to be sure a transfer out of the current player is happening before reducing the score.

**Comment by ultimatefiend** [comment]
FYI, this also effects relic transfers.  The scores go up and up on the UI even though the relics are just being passed between players.

**Pull request closed without merging**
