### PR TITLE
moved achievements, made spritesheets

### PR DESCRIPTION
**Pull request by normaljosh**
See issue #37 

- Moved special achievement card files to card_backgrounds folder
- removed action cards from card_backgrounds spritesheet
- made new spritesheet with special achievement and action cards

### CODE REVIEW

**Review by micahstairs — CHANGES_REQUESTED** [review]
Thanks! Can you please also leave the 5 achievement images in the original folder? I want the `cards` directory to be a complete list of the images we have to work with.

**Comment by normaljosh** [comment]
Sure thing! FYI I will be away from my computer until next Tues, so won't be able to work on any issues until then.

**Comment by micahstairs** [comment]
Thanks for the heads up. I also have a fairly busy few weeks coming up. I really appreciate all you've been contributing so far. Without a doubt, everyone's help is going to make this graphic refresh finish months before it would have otherwise. I feel like we are on track to have it ready by the end of October.

**Comment by micahstairs** [comment]
I'll merge it and fix those files myself.

**Review by micahstairs — APPROVED** [review]

**Pull request merged**
