### PR TITLE
Add game preference to use simplified graphics (#494)

### PR DESCRIPTION
**Pull request by micahstairs**
Screen Shot 2022-06-08 at 8 44 51 AM

### CODE REVIEW

**Review by ultimatefiend — COMMENTED** [review]
To distinguish between the number of cards and the age of the cards, could we add a "x" in from the of the number for the card count?  (or something else to make it obvious)

**Comment by micahstairs** [comment]
If we are going to make a change like that, should we look at making each column of cards take up less vertical space? I'm thinking ahead to when we have 5 different sets of cards being used at once. If things were condensed enough that we could have 5 columns side by side, that would make it easier to look at the decks and know what's going on.

**Comment by micahstairs** [comment]
I tried adding an `x` after the numbers, however, I wasn't able to do so because we are using BGA's counter UI component there and I think it's expecting to be working with integers.

**Comment by micahstairs** [comment]
@ultimatefiend  I understand there is still room for improvement here, but do you think this is more accessible to players than it was before this change? In other words, do you think we need to improve this further before we release or is it okay for now?

**Comment by ultimatefiend** [comment]
Yes, it is fine for now.

**Pull request merged**
