### PR TITLE
Make compact view show echo effects

### PR DESCRIPTION
**Pull request by micahstairs**
Requested in https://forum.boardgamearena.com/viewtopic.php?t=28777.

Screenshot 2023-01-19 at 11 49 00 AM
Screenshot 2023-01-19 at 11 49 05 AM
Screenshot 2023-01-19 at 11 53 01 AM
Screenshot 2023-01-19 at 11 53 06 AM
Screenshot 2023-01-19 at 11 53 15 AM
Screenshot 2023-01-19 at 11 53 22 AM

### CODE REVIEW

**Comment by micahstairs** [comment]
Never mind, this is not ready for review yet. I see some bugs involving the overall container height/width in certain splay orientations.

**Comment by ultimatefiend** [comment]
I was thinking this would be nice the other day. :)  I like the idea.

**Comment by micahstairs** [comment]
Great! I'll let you know when it's ready for review.

**Comment by micahstairs** [comment]
Alright I got everything working quite nicely!! It's ready for review.

**Review by ultimatefiend — APPROVED** [review]

**Pull request merged**
