### PR TITLE
Kahlia echoes age4

### PR DESCRIPTION
**Pull request by ultimatefiend**
All of the Age 4 cards are here.

The only problematic one is Barometer which requires a blue to be revealed while it is being returned.  I couldn't quite get that right.  The user should be prompted to reveal the blue card to prove their worthiness for Destiny, but I couldn't think of a good way to do that while the cards were being returned.

This fixes the bug in Almanac as well and some fixes for the card descriptions.

### CODE REVIEW

**Comment by ultimatefiend** [comment]
#448

**Comment by micahstairs** [comment]
For Barometer, here's an idea... If Destiny is still claimable and the player has at least one blue card, before getting them to return all of the cards from the forecast, first prompt them to reveal and return one blue card.

**Comment by ultimatefiend** [comment]
I thought about that, but then the player has to return the blue card first (which may not be desirable).

It could be a multi-level selection where they first reveal a blue card from their forecast (and then put it back) and then return all of the cards in their forecast.  If the first part succeeds, they would get Destiny.  It sounded really complicated, but might be a better option.

**Comment by micahstairs** [comment]
I like your suggestion! I'll let you implement that before I review your changes

**Comment by ultimatefiend** [comment]
Yeah, Barometer is a weird one. I'm not sure how you do it without revealing whether the player has a blue in their forecast when they don't want to go for Destiny.

**Comment by micahstairs** [comment]
With the wording on Destiny, I don't think players are allowed to not go for it?

**Comment by ultimatefiend** [comment]
You may return all of cards so they could elect to not go for it if they are about to get it anyway.

The problem is that you have to ask to reveal the blue cards before they are returned.  I guess they could just pass on the reveal of the blue card....maybe that will be sufficient?   They could theoretically still return their cards from their forecast at that point but I don't know why you would.

**Comment by ultimatefiend** [comment]
Some rewording on this text would really be helpful like :

"You may reveal and return a blue card from your forecast.  If you do, claim the Destiny achievement and return all cards from your forecast."

**Comment by micahstairs** [comment]
Ah yes, that would be more clear. I think proceeding with that as our
implementation is reasonable! Even though we won't actually be changing the
card's text.

**Comment by ultimatefiend** [comment]
Could you add it to the list of things to talk about in your next email to Carl?  I'd like to get his ok on the interpretation/implementation

**Comment by micahstairs** [comment]
Sure I'll ask him about it. I guess we can leave your implementation as-is for now and we can revisit this later.

Ready for me to review this?

**Comment by ultimatefiend** [comment]
No, let me do it as described above first.  RIght now it fails to run.

**Comment by micahstairs** [comment]
By above, I'll assume you mean: "You may reveal and return a blue card from your forecast. If you do, claim the Destiny achievement and return all cards from your forecast."

**Comment by ultimatefiend** [comment]
yes

**Comment by ultimatefiend** [comment]
ok good to review now

**Pull request merged**
