### PR TITLE
INNO-348: restored tool tip icons and did some refactoring

### PR DESCRIPTION
**Pull request by lordmcfuzz**

### CODE REVIEW

**Comment by lordmcfuzz** [comment]
might get a merge conflict with #346; what ever you decide to go with first, I can make sure everything is in its rightful place.

**Review by micahstairs — APPROVED** [review]

**Comment by micahstairs** [comment]
Alright, do you want to resolve the merge conflict now?

**Comment by lordmcfuzz** [comment]
Yeah I'll resolve it next chance I get.

**Comment by lordmcfuzz** [comment]
Merge conflict resolved, I'll let you merge it incase you want to give it a once over

**Comment by lordmcfuzz** [comment]
Ok good for review again

**Review by micahstairs — APPROVED** [review]

**Pull request merged**
