### PR TITLE
Make it possible for players to tell which type each card is

### PR DESCRIPTION
**Pull request by micahstairs**
This was requested in https://boardgamearena.com/bug?id=66491.

Screen Shot 2022-06-26 at 9 52 19 AM
Screen Shot 2022-06-26 at 9 57 27 AM

### CODE REVIEW

**Review by ultimatefiend — CHANGES_REQUESTED** [review]
I'd change the if else to a switch so it will be easier to maintain later.

Otherwise, it looks great.  I like the positioning of the text.

**Comment by micahstairs** [comment]
I agree that using a switch statement makes sense once the other expansions are added. I'll defer that change to the main-echoes branch, but I'm not in a rush to make that change in main-echoes either, because minimizing merge conflicts is helpful whenever I need to rebase main-echoes onto main-dev.

**Comment by ultimatefiend** [comment]
ok cool.  Don't forget about pushing it to main-echoes though. :)  Its a nice feature.

Would you add it after the alpha is released into production?

**Comment by micahstairs** [comment]
This will be included in the next push to alpha (and will be rebased into main-echoes next time I do a rebase). What I meant was that I'm not going to add the switch statement until later!

**Pull request merged**
