### PR TITLE
Inno 321 fix achievement width

### PR DESCRIPTION
**Pull request by lordmcfuzz**
dependent on #346

### CODE REVIEW

**Review by micahstairs — CHANGES_REQUESTED** [review]
When I resize my window on desktop, I can see the achievement zone changing size, but then I also see the reference card being cut off. Do you know why this is happening?

**Comment by lordmcfuzz** [comment]
So allot of our calculations are done on page load,  and from what I can tell this is online with bga games in general, so the whole responsive design that would be held to a standard of window resizing and the page perfectly reacting on the fly may not be easily achieved. I think we should shot for it, but incrementally. In classic bga fashion, "hit f5" when you have your page sized the way you want.

**Comment by micahstairs** [comment]
Okay that is a fair point!

Now that the other PRs are merged in, can you update this one so that I have a clean diff to review?

**Review by micahstairs — APPROVED** [review]
Thanks!

**Pull request merged**
